// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: internal/api/proto/timeline.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimelineService_GetTimeline_FullMethodName = "/api.TimelineService/GetTimeline"
)

// TimelineServiceClient is the client API for TimelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TimelineService definition
type TimelineServiceClient interface {
	GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TimelineChunk], error)
}

type timelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimelineServiceClient(cc grpc.ClientConnInterface) TimelineServiceClient {
	return &timelineServiceClient{cc}
}

func (c *timelineServiceClient) GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TimelineChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TimelineService_ServiceDesc.Streams[0], TimelineService_GetTimeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TimelineRequest, TimelineChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TimelineService_GetTimelineClient = grpc.ServerStreamingClient[TimelineChunk]

// TimelineServiceServer is the server API for TimelineService service.
// All implementations must embed UnimplementedTimelineServiceServer
// for forward compatibility.
//
// TimelineService definition
type TimelineServiceServer interface {
	GetTimeline(*TimelineRequest, grpc.ServerStreamingServer[TimelineChunk]) error
	mustEmbedUnimplementedTimelineServiceServer()
}

// UnimplementedTimelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimelineServiceServer struct{}

func (UnimplementedTimelineServiceServer) GetTimeline(*TimelineRequest, grpc.ServerStreamingServer[TimelineChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) mustEmbedUnimplementedTimelineServiceServer() {}
func (UnimplementedTimelineServiceServer) testEmbeddedByValue()                         {}

// UnsafeTimelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimelineServiceServer will
// result in compilation errors.
type UnsafeTimelineServiceServer interface {
	mustEmbedUnimplementedTimelineServiceServer()
}

func RegisterTimelineServiceServer(s grpc.ServiceRegistrar, srv TimelineServiceServer) {
	// If the following call pancis, it indicates UnimplementedTimelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimelineService_ServiceDesc, srv)
}

func _TimelineService_GetTimeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TimelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimelineServiceServer).GetTimeline(m, &grpc.GenericServerStream[TimelineRequest, TimelineChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TimelineService_GetTimelineServer = grpc.ServerStreamingServer[TimelineChunk]

// TimelineService_ServiceDesc is the grpc.ServiceDesc for TimelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TimelineService",
	HandlerType: (*TimelineServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTimeline",
			Handler:       _TimelineService_GetTimeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/api/proto/timeline.proto",
}
