---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: workloads
data:
  LOG_LEVEL: "info"
  ENABLE_CORS: "true"
  CORS_ORIGINS: "https://example.com,https://app.example.com"
  RATE_LIMIT: "1000"
  AUTH_SERVICE_URL: "http://auth-service.workloads.svc.cluster.local"
  UPSTREAM_TIMEOUT: "30s"
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: workloads
  labels:
    app: gateway
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: gateway
        image: busybox:1.35
        command: ["sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        envFrom:
        - configMapRef:
            name: gateway-config
        ports:
        - containerPort: 8080
          name: http
