---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
  namespace: workloads
data:
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "orders"
  LOG_LEVEL: "info"
  SERVICE_TIMEOUT: "30s"
  PAYMENT_SERVICE_URL: "http://payment-api.workloads.svc.cluster.local"
  KAFKA_BROKERS: "kafka-0.kafka.default.svc.cluster.local:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: workloads
  labels:
    app: order-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: order-api
        image: busybox:1.35
        command: ["sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        envFrom:
        - configMapRef:
            name: order-api-config
