//go:build disabled

package reviewer

import (
	"google.golang.org/adk/agent"
	"google.golang.org/adk/agent/llmagent"
	"google.golang.org/adk/model"
	"google.golang.org/adk/tool"
)

// AgentName is the name of the Incident Reviewer Agent.
const AgentName = "incident_reviewer_agent"

// AgentDescription is the description of the Incident Reviewer Agent for the coordinator.
const AgentDescription = "Reviews and validates hypotheses generated by the builder. Approves, modifies, or rejects based on quality criteria including falsifiability, evidence strength, and confidence calibration."

// New creates a new Incident Reviewer Agent.
// The agent reviews hypotheses from the builder and applies quality gates.
func New(llm model.LLM) (agent.Agent, error) {
	// Create the submit_reviewed_hypotheses tool
	submitTool, err := NewSubmitReviewedHypothesesTool()
	if err != nil {
		return nil, err
	}

	return llmagent.New(llmagent.Config{
		Name:        AgentName,
		Description: AgentDescription,
		Model:       llm,
		Instruction: SystemPrompt,
		Tools:       []tool.Tool{submitTool},
		// Include conversation history so the agent can see previous context
		IncludeContents: llmagent.IncludeContentsDefault,
	})
}
