---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: "3.0.8"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    replicaCount: 1
    config:
      webhooks:
      - namespaceSelector:
          matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
            - kyverno
            - flux-system
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    serviceAccount:
      create: true
  targetNamespace: kyverno
  install:
    createNamespace: false
  dependsOn:
  - name: cert-manager
    namespace: flux-system
