export const HEADLINES = [
    { head: "config changes.", sub: "The other 20% are just config changes you haven’t found yet." },
    { head: "defaults.", sub: "Defaults you never agreed to." },
    { head: "annotations.", sub: "The smallest footgun." },
    { head: "config maps.", sub: "Hot reloaded, cold sweats." },
    { head: "sync delays.", sub: "Eventually consistent. Eventually broken." },
    { head: "env vars.", sub: "Strings with opinions." },
    { head: "secrets rotation.", sub: "Security improved. Availability not so much." },
    { head: "CRDs.", sub: "Custom problems, custom outages." },
    { head: "YAML.", sub: "Two spaces. Or three. Or chaos." },
    { head: "rollout restarts.", sub: "Have you tried turning prod off and on again?" },
    { head: "permissions.", sub: "It worked yesterday." },
    { head: "kubectl apply.", sub: "Applied directly to production." },
    { head: "Helm values.", sub: "Somewhere, a boolean flipped." },
    { head: "feature flags.", sub: "Flags down, incident up." },
    { head: "missing context.", sub: "The cluster remembers. You don’t." },
    { head: "partial rollouts.", sub: "Half new, half broken." },
    { head: "scaling events.", sub: "Congrats, it worked too well." },
    { head: "traffic shifting.", sub: "Gradual, until it wasn’t." },
    { head: "Friday deploys.", sub: "Statistically speaking." },
    { head: "config churn.", sub: "Death by a thousand applies." },
    { head: "rollout timing.", sub: "Right change. Wrong moment." }, 
    { head: "timeouts.", sub: "Configured once. Forgotten forever." },
    { head: "retries.", sub: "Because what could go wrong with more traffic?" },
    { head: "autoscaling.", sub: "The cure that becomes the disease." },
    { head: "entropy.", sub: "Distributed systems, baby." },
    { head: "humans.", sub: "Armed with kubectl." },
];

export const NAV_LINKS = [
    { name: 'Features', href: '#features' },
    { name: 'How it Works', href: '#how-it-works' },
    { name: 'Integration', href: '#integration' },
    { name: 'Pricing', href: '#pricing' },
];