// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/api/proto/timeline.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/moolen/spectre/internal/api/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TimelineServiceName is the fully-qualified name of the TimelineService service.
	TimelineServiceName = "api.TimelineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TimelineServiceGetTimelineProcedure is the fully-qualified name of the TimelineService's
	// GetTimeline RPC.
	TimelineServiceGetTimelineProcedure = "/api.TimelineService/GetTimeline"
)

// TimelineServiceClient is a client for the api.TimelineService service.
type TimelineServiceClient interface {
	GetTimeline(context.Context, *connect.Request[pb.TimelineRequest]) (*connect.ServerStreamForClient[pb.TimelineChunk], error)
}

// NewTimelineServiceClient constructs a client for the api.TimelineService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTimelineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TimelineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	timelineServiceMethods := pb.File_internal_api_proto_timeline_proto.Services().ByName("TimelineService").Methods()
	return &timelineServiceClient{
		getTimeline: connect.NewClient[pb.TimelineRequest, pb.TimelineChunk](
			httpClient,
			baseURL+TimelineServiceGetTimelineProcedure,
			connect.WithSchema(timelineServiceMethods.ByName("GetTimeline")),
			connect.WithClientOptions(opts...),
		),
	}
}

// timelineServiceClient implements TimelineServiceClient.
type timelineServiceClient struct {
	getTimeline *connect.Client[pb.TimelineRequest, pb.TimelineChunk]
}

// GetTimeline calls api.TimelineService.GetTimeline.
func (c *timelineServiceClient) GetTimeline(ctx context.Context, req *connect.Request[pb.TimelineRequest]) (*connect.ServerStreamForClient[pb.TimelineChunk], error) {
	return c.getTimeline.CallServerStream(ctx, req)
}

// TimelineServiceHandler is an implementation of the api.TimelineService service.
type TimelineServiceHandler interface {
	GetTimeline(context.Context, *connect.Request[pb.TimelineRequest], *connect.ServerStream[pb.TimelineChunk]) error
}

// NewTimelineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTimelineServiceHandler(svc TimelineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	timelineServiceMethods := pb.File_internal_api_proto_timeline_proto.Services().ByName("TimelineService").Methods()
	timelineServiceGetTimelineHandler := connect.NewServerStreamHandler(
		TimelineServiceGetTimelineProcedure,
		svc.GetTimeline,
		connect.WithSchema(timelineServiceMethods.ByName("GetTimeline")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.TimelineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TimelineServiceGetTimelineProcedure:
			timelineServiceGetTimelineHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTimelineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTimelineServiceHandler struct{}

func (UnimplementedTimelineServiceHandler) GetTimeline(context.Context, *connect.Request[pb.TimelineRequest], *connect.ServerStream[pb.TimelineChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.TimelineService.GetTimeline is not implemented"))
}
